version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
    open-pull-requests-limit: 99
    labels:
      - dependabot
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: 'weekly'
    labels:
      - dependabot
