name: transifex-pull-request-action
description: Fetches translations from transifex and proposes a pull request to merge these.
author: Camptocamp Association
inputs:
  transifex_token:
    description: Transifex token
    required: true
  transifex_project:
    description: Transifex transifexProject
    required: true
  transifex_resource:
    description: Transifex resource
    required: true
  locales:
    description: A list of locales to fetch, separated by commas
    required: true
  github_token:
    description: Github secret
    required: true
  branch:
    description: Branch used for pull request
    required: false
    default: transifex/i18n-updates
runs:
  using: 'node12'
  main: 'dist/index.js'
