name: transifex-pull-request-action
description: Fetches translations from transifex and proposes a pull request to merge these.
author: Camptocamp Association
inputs:
  transifex_token:
    description: Transifex token
    required: true
  transifex_organisation:
    description: Transifex organisation
    required: true
  transifex_project:
    description: Transifex project
    required: true
  transifex_resource:
    description: Transifex resource
    required: true
  output:
    description: Folder where to output files
    required: true
  locales:
    description: A list of locales to fetch, separated by commas
    required: true
  github_token:
    description: Github secret
    required: true
  branch:
    description: Branch used for pull request
    required: false
    default: transifex/i18n-updates
  base_branch:
    description: The target branch into which the pull request will be merged
  transform:
    description: Transformation to apply to translation files. One of `none` or `po-to-json`
  labels:
    description: Labels to associate to the pull request
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'
